# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [9]:
print(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
None


#### 3. Create a null vector of size 10 (★☆☆)

In [10]:
n = np.zeros(10)
print(n)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆)

In [11]:
n = np.zeros((4,4))
print("%d bytes" % (n.size * n.itemsize))

128 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
%run `python -c "import numpy; http://numpy.info(numpy.add)"`

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
arr = np.zeros(10)
ar[4] = 1
print(arr)

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
arr = np.arange(10,50)
print(arr)

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
arr = np.arange(50)
arr = arr[::-1]
print(arr)

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [7]:
arr = np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [6]:
arr = np.array([1, 2, 0, 0, 4, 0])
np.where(arr != 0)[0]

array([0, 1, 4])

#### 11. Create a 3x3 identity matrix (★☆☆)

In [8]:
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
arr = np.random.random((3, 3, 3))
print(arr)

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
x = np.random.random((10, 10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum Value: ", xmin)
print("Maximum Value: ", xmax)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
Z = np.random.random(30)
n = Z.mean()
print(n)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
x = np.ones((10, 10))
x[1:-1,1:-1] = 0
print(x)

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
n = np.ones((5,5))
n = np.pad(n, pad_width=1, mode='constant', constant_values=0)
print(n)

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
nan
False
False
nan
True
False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
n = np.arange(1,5) # create an 1x5 array 
# print(x)
arr = np.diag(n, k=-1) #construct a diagonal array 
print(arr) 

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
n = np.zeros((8,8),dtype=int)
n[1::2,::2] = 1
n[::2,1::2] = 1
print(n)

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
print(np.unravel_index(100,(6,7,8)))

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
n = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(n)

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
n = np.random.random((5,5))
n = (n - np.mean (n)) / (np.std (n))
print(n)

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
rbg_color = np.dtype([("r", np.ubyte, 1),
                      ("g", np.ubyte, 1),
                      ("b", np.ubyte, 1),
                      ("a", np.ubyte, 1)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [12]:
n = np.dot(np.ones((5,3)), np.ones((3,2)))
print(n)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
n = np.arange(11)
n[(n > 3) & (n <= 8)] *= -1
print(n)

#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
9
10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z**Z
Z/1/1

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
nan
0
[-9.22337204e+18]

#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
n = np.random.uniform(-10,+10,10)
print(n)
print(np.ceil(np.abs(n))) 
# print (np.copysign(np.ceil(np.abs(n)), n)) # if add negative numbers together

#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
import numpy as np

# first array
array1 = np.array([0, 10, 20, 40, 60]) 
print("1st Array: ",array1)

# second array
array2 = [10, 30, 40]
print("2nd Array: ",array2)

print("Common values between two arrays:", np.intersect1d(array1, array2))

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
# seterr -> Set how floating-point errors are handled
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Better keep defaults
_ = np.seterr(**defaults)

An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
import numpy as np

# range of date
arr = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(arr)

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [ ]:
n = np.random.uniform(0,10,10)
print(n)
print (n.astype(int)) #Return int
print(ceil(n)) #Return the ceiling of the number (round up).
print(floor(n)) #Return the floor of the number (round down).
print(rint(n)) #Round elements of the array to the nearest integer
print(trunc(n)) #Return the truncated value

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
arr = np.random.randint(0,5,25).reshape(5,5)
print(arr)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def generator(max_value):
    arr = np.random.randint(0,max_value,10)
    return arr

generator(100)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
arr = np.random.random(10)
print(arr)

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
arr = np.random.randint(0,4,10) # random int numbers
arr = np.sort(arr)
print(arr)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
x = np.random.randint(0, 2, 5)
y = np.random.randint(0, 2, 5)

# Arrays with the same shape
equal = np.allclose(x,y)
print(equal)

# Check if it's exactly the same
equal = np.array_equal(x,y)
print(equal)

#### 43. Make an array immutable (read-only) (★★☆)

In [13]:
n = np.zeros(10)
n.flags.writeable = False
n[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
n = np.random.random((10,2))
x = n[:,0], 
y = n[:,1]
a = np.power(x,2) + np.power(y,2)
b = np.arctan2(y,x)
print(a)
print(b)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
n = np.random.random(10)
n[n.argmax()] = 0
print(n)

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [ ]:
arr = np.random.random((5,2))
# print(arr)
x = arr[:,0]
#print(x)
y = arr[:,1]
#print(y)
print(np.meshgrid(x,y))

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

In [ ]:
arr = np.arange(10).reshape(2,5)
print(arr)
arr[[0,1]] = arr[[1,0]]
print(arr)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [ ]:
array = np.random.randint(2,6, size=(3,3))
print (array)
a = np.cumsum(array)
print("\n")
print (a)
print ("Average:", round(np.average(a),2))

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)