In [5]:
# Import the needed libraries
import numpy as np

**72. How to swap two rows of an array?** 

In [6]:
# same principle as a,b = b,a on python variables
arr = np.arange(10).reshape(2,5)
print(arr)
arr[[0,1]] = arr[[1,0]]
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[5 6 7 8 9]
 [0 1 2 3 4]]


**75. How to compute averages using a sliding window over an array?**

In [7]:
array = np.random.randint(2,6, size=(3,3))
# first print the array
print (array)
a = np.cumsum(array)
print("\n")
# print the sum of the matrix -> 2, then 2+5=7, then 7+4=11, then 11+5=16
print (a)
print ("Average:", round(np.average(a),2))

[[2 5 4]
 [5 3 4]
 [4 5 5]]


[ 2  7 11 16 19 23 27 32 37]
Average: 19.33
