In [ ]:
# Import the needed libraries

**13. Create a 10x10 array with random values and find the minimum and maximum values**

In [6]:
import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum Value: ", xmin)
print("Maximum Value: ", xmax)

Original Array:
[[0.99372001 0.06593564 0.44037016 0.05316323 0.02599786 0.40218487
  0.27144505 0.10649024 0.44686493 0.8448535 ]
 [0.49764405 0.22756313 0.03425712 0.65828417 0.50582715 0.8610883
  0.65613091 0.65556834 0.40238439 0.03284365]
 [0.89543765 0.74967017 0.38757658 0.92710205 0.77561023 0.46206758
  0.77749501 0.02331833 0.34624757 0.34510868]
 [0.19325792 0.24916846 0.1912085  0.38702745 0.19864032 0.02162651
  0.23571469 0.04448769 0.96519805 0.65286085]
 [0.29971957 0.10686993 0.51405908 0.8492499  0.05244143 0.20731996
  0.04422827 0.15545016 0.69439632 0.83312659]
 [0.14688951 0.35261073 0.33960653 0.53092361 0.92285981 0.10391055
  0.94312671 0.63016003 0.49255772 0.53084911]
 [0.19305663 0.65889533 0.68810678 0.61132412 0.18181701 0.25827252
  0.792581   0.66647965 0.24796013 0.95830762]
 [0.0414651  0.99174434 0.03418896 0.2742213  0.94048152 0.48847593
  0.50535521 0.37081542 0.00206646 0.19512355]
 [0.08022115 0.12859198 0.78980928 0.99097752 0.35845064 0.715170

**15. Create a 2d array with 1 on the border and 0 inside**

In [9]:
import numpy as np
x = np.ones((10,10))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
